### ISSUE TITLE
max read depth

### ISSUE THREAD

**Issue by Patrick-Reed** [brendanofallon/SNPSVM#1]
Does SNPSVM enforce a maximum read depth, not using more than X many reads to call a variant.  I'm using haloplex so read depth is an issue.

**Comment by brendanofallon** [comment]
There's currently no maximum read depth. Individual metrics may do some downsampling, but there's no general maximum.

By the way, this issues page is usually used for bug tracking, feature requests, etc. If you have a question about how SNPSVM works feel free to email me at the email address on the SNPSVM paper. Thanks for your interest.
